services:
  homeassistant:
    container_name: homeassistant
    image: ghcr.io/home-assistant/home-assistant:stable
    network_mode: host
    restart: unless-stopped
    env_file: .env
    environment:
      - TZ=${TZ}
    volumes:
      - ${HA_CONFIG_DIR}:/config:Z

  whisper:
    container_name: whisper
    image: docker.io/rhasspy/wyoming-whisper
    restart: unless-stopped
    command: --model ${WHISPER_MODEL} --language ${WHISPER_LANGUAGE} --compute-type ${WHISPER_COMPUTE_TYPE}
    volumes:
      - ${WHISPER_DATA_DIR}:/data:Z
    ports:
      - "10300:10300"

  piper:
    container_name: piper
    image: docker.io/rhasspy/wyoming-piper
    restart: unless-stopped
    command: --voice ${PIPER_VOICE} --data-dir /data --download-dir /data
    volumes:
      - ${PIPER_DATA_DIR}:/data:Z
    ports:
      - "10200:10200"
